include(OptionsWindows)

add_definitions(/D_WIN32_WINNT=0x0603 /DWINVER=0x0603) # Windows 8.1

if (MSVC_CXX_ARCHITECTURE_ID STREQUAL ARM)
	add_definitions(/DWTF_CPU_ARM_THUMB2 /DWTF_CPU_ARM_NEON)
endif ()

set(ENABLE_LLINT_C_LOOP ON)
set(ENABLE_JIT OFF)
set(WTF_USE_ICU_UNICODE OFF)
set(WTF_USE_NLS_UNICODE ON)
add_definitions(/DENABLE_ASSEMBLER=0 /DENABLE_YARR_JIT=0)
